### ISSUE TITLE
US04.09.01 - As an owner or borrower, I can browse all past and current trades involving me as either borrower or owner. I should be able to look at my trades and trades offered to me.

### ISSUE THREAD

**Issue by udeyrishi** [CMPUT301F15T03/301p#52] opened 2015-09-29 23:18 UTC

**Comment by rosshamish** [comment] 2015-10-07 17:32
Duplicate of #51 "As an owner or borrower, I can browse all past and current trades involving me." ?

**Comment by mabuyo** [comment] 2015-10-09 20:26
See [use case] (https://github.com/CMPUT301F15T03/301p/wiki/1.4-Use-Cases-%5BTrading%5D) 1.4.8

**Comment by rosshamish** [comment] 2015-11-28 23:43
This is done!

**Closed by rosshamish** 2015-11-28 23:43 UTC
Labels: trade with friends
